name: instabug_http_client
description:
  This package is an add on to instabug_flutter. It intercepts any requests performed
  with http Package and sends them to the report that will be sent to the dashboard.
publish_to: http://nexus.gojitsu.com:7777
version: 3.2.0-nexus.1
homepage: https://github.com/Instabug/Instabug-Flutter#readme

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  instabug_flutter: ^13.2.0
  meta: ^1.11.0
  watcher: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

