name: instabug_http_client
description:
  This package is an add on to instabug_flutter. It intercepts any requests performed
  with http Package and sends them to the report that will be sent to the dashboard.
version: 2.6.0-filtercontent.1
publish_to: http://nexus.axlehire.com:7777
homepage: https://github.com/axlehire/Instabug-Dart-http-Adapter#readme
axlehire_project_type: package

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  instabug_flutter: '>=11.0.0 <13.0.0'
  meta: ^1.9.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
